clear
atom = getAtom("Lithium7");
laser = Laser( ...
    wavelength = 1064e-9,...
    direction = [0;1;0],...
    polarization = [0;0;1],...
    intensity = 3.852874965460643e7 ...
    );
laser = {laser};
ol = OpticalLattice(atom,laser{1});
ol.DepthSpec = 12.32 * ol.RecoilEnergy;
ol.updateIntensity;
kL = ol.Laser.AngularWavenumber;
laser = {ol.Laser};

power = (1.26 + 1.44)/2;
rescaledPower = power * 20 / 55;
separation = 680.6762e-6;

wLaser1 = GaussianBeam( ...
    wavelength = 532e-9,...
    direction = [0;0;1],...
    polarization = [0;1;0],...
    power = rescaledPower,...
    waist = [20;20]*1e-6,...
    center = [0;-separation/2;0]...
    );
wLaser2 = GaussianBeam( ...
    wavelength = 532e-9,...
    direction = [0;0;1],...
    polarization = [0;1;0],...
    power = rescaledPower,...
    waist = [20;20]*1e-6,...
    center = [0;separation/2;0]...
    );
wLaser = [wLaser1,wLaser2];
wLaser = {wLaser};

% initial condition

nic = 20;
for ii = 1:nic
    ic(ii) = InitialCondition("SeSim1D");
end
se = LatticeSeSim1D("DrivenCavity", ...
    atom=atom,...
    laser = laser,...
    wallLaser = wLaser,...
    initialCondition = ic,...
    timeStep=1e-7,...
    totalTime=80e-3,...
    spaceRange = 750e-06,...
    spaceStep = 1e-8);

sigma = 25e-6;
x = se.SimRun(1).SpaceList;
x = x.';
qlist = linspace(0.6,0.95,nic);
for ii = 1:nic
    qIni = qlist(ii)*kL;
    [~,~,phi] = ol.computeBand1D(qIni,2,x);
    tExp = 20e-3;
    hbar = Constants.SI("hbar");
    M = atom.mass;
    psi = (sqrt(2*pi*sigma^2)*(1+1i*hbar*tExp/2/M/sigma^2))^(-1/2) * ...
        exp(-(x).^2/4/sigma^2/(1+1i*hbar*tExp/2/M/sigma^2)) .* phi;
    ic(ii).WaveFunction = psi;
end
for ii = 1:se.NRun
    se.SimRun(ii).InitialCondition = ic(ii);
end
se.SavePeriod = 1e4;
se.AveragePeriod = 200;
se.Description = "Driven cavity TDSE simulation.";
se.updateTrialType;
se.start
%% Data analysis
% se = loadSim(70,"LatticeSeSim1D","DrivenCavity");
fList = zeros(1,se.NRun);
peakList = cell(1,se.NRun);
for ii = 1:se.NRun
    peak = se.SimRun(ii).showPeak;
    fd = IsoscelesTriangleFit1D(peak);
    fd.do;
    fList(ii) = 1/fd.Coefficient(4);
    peakList{ii} = peak;
end